// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: 06LibraryMgmt_GRPC/grpc/protoFile/lms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Book Structure
type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

//Create Book
type CreateBookReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *CreateBookReq) Reset() {
	*x = CreateBookReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookReq) ProtoMessage() {}

func (x *CreateBookReq) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookReq.ProtoReflect.Descriptor instead.
func (*CreateBookReq) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookReq) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type CreateBookRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *CreateBookRes) Reset() {
	*x = CreateBookRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRes) ProtoMessage() {}

func (x *CreateBookRes) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRes.ProtoReflect.Descriptor instead.
func (*CreateBookRes) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookRes) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

//List All Books
type ListAllBooksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAllBooksReq) Reset() {
	*x = ListAllBooksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllBooksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllBooksReq) ProtoMessage() {}

func (x *ListAllBooksReq) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllBooksReq.ProtoReflect.Descriptor instead.
func (*ListAllBooksReq) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{3}
}

type ListAllBooksRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=Book,proto3" json:"Book,omitempty"`
}

func (x *ListAllBooksRes) Reset() {
	*x = ListAllBooksRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllBooksRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllBooksRes) ProtoMessage() {}

func (x *ListAllBooksRes) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllBooksRes.ProtoReflect.Descriptor instead.
func (*ListAllBooksRes) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllBooksRes) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

//Search Book
type SearchBooksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Search:
	//	*SearchBooksReq_Title
	//	*SearchBooksReq_Author
	Search isSearchBooksReq_Search `protobuf_oneof:"search"`
}

func (x *SearchBooksReq) Reset() {
	*x = SearchBooksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBooksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBooksReq) ProtoMessage() {}

func (x *SearchBooksReq) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBooksReq.ProtoReflect.Descriptor instead.
func (*SearchBooksReq) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{5}
}

func (m *SearchBooksReq) GetSearch() isSearchBooksReq_Search {
	if m != nil {
		return m.Search
	}
	return nil
}

func (x *SearchBooksReq) GetTitle() string {
	if x, ok := x.GetSearch().(*SearchBooksReq_Title); ok {
		return x.Title
	}
	return ""
}

func (x *SearchBooksReq) GetAuthor() string {
	if x, ok := x.GetSearch().(*SearchBooksReq_Author); ok {
		return x.Author
	}
	return ""
}

type isSearchBooksReq_Search interface {
	isSearchBooksReq_Search()
}

type SearchBooksReq_Title struct {
	Title string `protobuf:"bytes,1,opt,name=title,proto3,oneof"`
}

type SearchBooksReq_Author struct {
	Author string `protobuf:"bytes,2,opt,name=author,proto3,oneof"`
}

func (*SearchBooksReq_Title) isSearchBooksReq_Search() {}

func (*SearchBooksReq_Author) isSearchBooksReq_Search() {}

type SearchBooksRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *SearchBooksRes) Reset() {
	*x = SearchBooksRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBooksRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBooksRes) ProtoMessage() {}

func (x *SearchBooksRes) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBooksRes.ProtoReflect.Descriptor instead.
func (*SearchBooksRes) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{6}
}

func (x *SearchBooksRes) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

//Update Book
type UpdateBookReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *UpdateBookReq) Reset() {
	*x = UpdateBookReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookReq) ProtoMessage() {}

func (x *UpdateBookReq) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookReq.ProtoReflect.Descriptor instead.
func (*UpdateBookReq) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBookReq) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type UpdateBookRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *UpdateBookRes) Reset() {
	*x = UpdateBookRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBookRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRes) ProtoMessage() {}

func (x *UpdateBookRes) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRes.ProtoReflect.Descriptor instead.
func (*UpdateBookRes) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBookRes) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

//Delete Book
type DeleteBookReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBookReq) Reset() {
	*x = DeleteBookReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookReq) ProtoMessage() {}

func (x *DeleteBookReq) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookReq.ProtoReflect.Descriptor instead.
func (*DeleteBookReq) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBookReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBookRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteBookRes) Reset() {
	*x = DeleteBookRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRes) ProtoMessage() {}

func (x *DeleteBookRes) ProtoReflect() protoreflect.Message {
	mi := &file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRes.ProtoReflect.Descriptor instead.
func (*DeleteBookRes) Descriptor() ([]byte, []int) {
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBookRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto protoreflect.FileDescriptor

var file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x30, 0x36, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x4d, 0x67, 0x6d, 0x74, 0x5f,
	0x47, 0x52, 0x50, 0x43, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46,
	0x69, 0x6c, 0x65, 0x2f, 0x6c, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x44, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x34,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x23, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04,
	0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x34, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x22, 0x36, 0x0a,
	0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x12, 0x23, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x4c, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x22, 0x35, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x34, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x04, 0x62,
	0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b,
	0x22, 0x34, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65,
	0x73, 0x12, 0x23, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x32, 0xe3, 0x02, 0x0a, 0x0a, 0x4c, 0x6d, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x40, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x12, 0x48, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x30, 0x01, 0x12, 0x45, 0x0a,
	0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46,
	0x69, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x42, 0x1c, 0x5a, 0x1a, 0x30, 0x36, 0x4c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x4d, 0x67, 0x6d, 0x74, 0x5f, 0x47, 0x52, 0x50, 0x43, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescOnce sync.Once
	file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescData = file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDesc
)

func file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescGZIP() []byte {
	file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescOnce.Do(func() {
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescData = protoimpl.X.CompressGZIP(file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescData)
	})
	return file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDescData
}

var file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_goTypes = []interface{}{
	(*Book)(nil),            // 0: protoFile.Book
	(*CreateBookReq)(nil),   // 1: protoFile.CreateBookReq
	(*CreateBookRes)(nil),   // 2: protoFile.CreateBookRes
	(*ListAllBooksReq)(nil), // 3: protoFile.ListAllBooksReq
	(*ListAllBooksRes)(nil), // 4: protoFile.ListAllBooksRes
	(*SearchBooksReq)(nil),  // 5: protoFile.SearchBooksReq
	(*SearchBooksRes)(nil),  // 6: protoFile.SearchBooksRes
	(*UpdateBookReq)(nil),   // 7: protoFile.UpdateBookReq
	(*UpdateBookRes)(nil),   // 8: protoFile.UpdateBookRes
	(*DeleteBookReq)(nil),   // 9: protoFile.DeleteBookReq
	(*DeleteBookRes)(nil),   // 10: protoFile.DeleteBookRes
}
var file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_depIdxs = []int32{
	0,  // 0: protoFile.CreateBookReq.book:type_name -> protoFile.Book
	0,  // 1: protoFile.CreateBookRes.book:type_name -> protoFile.Book
	0,  // 2: protoFile.ListAllBooksRes.Book:type_name -> protoFile.Book
	0,  // 3: protoFile.SearchBooksRes.book:type_name -> protoFile.Book
	0,  // 4: protoFile.UpdateBookReq.book:type_name -> protoFile.Book
	0,  // 5: protoFile.UpdateBookRes.book:type_name -> protoFile.Book
	1,  // 6: protoFile.LmsService.CreateBook:input_type -> protoFile.CreateBookReq
	3,  // 7: protoFile.LmsService.ListAllBooks:input_type -> protoFile.ListAllBooksReq
	5,  // 8: protoFile.LmsService.SearchBooks:input_type -> protoFile.SearchBooksReq
	7,  // 9: protoFile.LmsService.UpdateBook:input_type -> protoFile.UpdateBookReq
	9,  // 10: protoFile.LmsService.DeleteBook:input_type -> protoFile.DeleteBookReq
	2,  // 11: protoFile.LmsService.CreateBook:output_type -> protoFile.CreateBookRes
	4,  // 12: protoFile.LmsService.ListAllBooks:output_type -> protoFile.ListAllBooksRes
	6,  // 13: protoFile.LmsService.SearchBooks:output_type -> protoFile.SearchBooksRes
	8,  // 14: protoFile.LmsService.UpdateBook:output_type -> protoFile.UpdateBookRes
	10, // 15: protoFile.LmsService.DeleteBook:output_type -> protoFile.DeleteBookRes
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_init() }
func file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_init() {
	if File__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllBooksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllBooksRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBooksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBooksRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBookReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBookRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*SearchBooksReq_Title)(nil),
		(*SearchBooksReq_Author)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_goTypes,
		DependencyIndexes: file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_depIdxs,
		MessageInfos:      file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_msgTypes,
	}.Build()
	File__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto = out.File
	file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_rawDesc = nil
	file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_goTypes = nil
	file__06LibraryMgmt_GRPC_grpc_protoFile_lms_proto_depIdxs = nil
}
